services:
  php:
    image: laravel-ben
    build: .
    restart: always
    ports:
      - "8090:80" # HTTP
      - "8443:443" # HTTPS
      - "8443:443/udp" # HTTP/3
    volumes:
      - './test-docker/database.sqlite:/app/database/database.sqlite'
      - './test-docker/public:/app/storage/app/public'
      - './test-docker/private:/app/storage/app/private'
      - './test-docker/caddy_data:/data/caddy'
      - './test-docker/caddy_config:/config/caddy'
      - backup-repo:/backup
    tty: true
    environment:
      APP_URL: "http://localhost:8090"
      APP_RUN_MIGRATIONS: "true"
      BACKUP_DB_PATH: "/app/database/database.sqlite"
      BACKUP_STORAGE_PATH: "/app/storage/app"
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}

  worker:
    image: laravel-ben
    restart: always
    volumes:
      - './test-docker/database.sqlite:/app/database/database.sqlite'
      - './test-docker/public:/app/storage/app/public'
      - './test-docker/private:/app/storage/app/private'
      - backup-repo:/backup
    environment:
      APP_URL: "http://localhost:8090"
      BACKUP_DB_PATH: "/app/database/database.sqlite"
      BACKUP_STORAGE_PATH: "/app/storage/app"
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: >
      sh -c "php artisan queue:work --tries=3 &
             php artisan schedule:work"

volumes:
  backup-repo: