services:
  php:
    image: laravel-ben
    build: .
    # uncomment the following line if you want to run this in a production environment
    restart: always
    ports:
      - "8090:80" # HTTP
      - "8443:443" # HTTPS
      - "8443:443/udp" # HTTP/3
    volumes:
      - './test-docker/database.sqlite:/app/database/database.sqlite'
      - './test-docker/public:/app/storage/app/public'
      - './test-docker/private:/app/storage/app/private'
      - './test-docker/caddy_data:/data/caddy'
      - './test-docker/caddy_config:/config/caddy'
      - backup-repo:/backup
    # comment the following line in production, it allows to have nice human-readable logs in dev
    tty: true
    environment:
      APP_URL: "http://localhost:8090"
      APP_RUN_MIGRATIONS: "true"
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}

  worker:
    image: laravel-ben
    restart: always
    volumes:
      - './test-docker/database.sqlite:/app/database/database.sqlite'
      - './test-docker/public:/app/storage/app/public'
      - './test-docker/private:/app/storage/app/private'
    environment:
      APP_URL: "http://localhost:8090"
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    command: php artisan queue:work --tries=3

volumes:
  backup-repo:
